# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{auto-bidder}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chad Boyd"]
  s.date = %q{2010-07-10}
  s.description = %q{gem for automatically placing bids on auction sites}
  s.email = %q{hoverlover@gmail.com}
  s.executables = ["auto-bidder", "auto-bidder"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    "bin/auto-bidder",
     "lib/auto_bidder.rb",
     "lib/auto_bidder/auction_interface.rb",
     "lib/auto_bidder/bigdeal.rb",
     "lib/auto_bidder/browser_interface.rb"
  ]
  s.homepage = %q{http://github.com/hoverlover/auto-bidder}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{gem for automatically placing bids on auction sites}
  s.test_files = [
    "spec/auto_bidder_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<safariwatir>, [">= 0.3.7"])
    else
      s.add_dependency(%q<safariwatir>, [">= 0.3.7"])
    end
  else
    s.add_dependency(%q<safariwatir>, [">= 0.3.7"])
  end
end

